site_name: pypsa-at
docs_dir: docs-at
repo_url: https://github.com/aggm-ag/pypsa-at
edit_uri: docs-at
site_dir: public
site_url: https://pypsa-at.readthedocs.io

nav:
- Home: index.md
- Limitations: limitations.md
- How-to-Guides:
  - how-to-guides/index.md
  - Working with Evaluations: how-to-guides/evals.md
  - Production Targets: how-to-guides/production-targets.md
- Tutorials:
  - tutorials/index.md
  - tutorials/model-modifications.md
- Data Sources: data_sources.md
- Function Reference:
  - Modifications:
    - reference/mods/index.md
    - clustering: reference/mods/clustering.md
    - Constraints:
      - reference/mods/constraints/index.md
      - co2_budget.py: reference/mods/constraints/co2_budget.md
      - eag.py: reference/mods/constraints/eag.md
      - tyndp.py: reference/mods/constraints/tyndp.md
      - trajectories.py: reference/mods/constraints/trajectories.md
    - Network:
      - reference/mods/network/index.md
      - common.py: reference/mods/network/common.md
      - electricity.py: reference/mods/network/electricity.md
      - gas.py: reference/mods/network/gas.md
      - h2.py: reference/mods/network/h2.md
      - hydro.py: reference/mods/network/hydro.md
      - trajectories.py: reference/mods/network/trajectories.md
      - potentials.py: reference/mods/network/potentials.md
  - Evaluations:
    - reference/evals/index.md
    - cli.py: reference/evals/cli.md
    - constants.py: reference/evals/constants.md
    - fileio.py: reference/evals/fileio.md
    - stats.py: reference/evals/stats.md
    - utils.py: reference/evals/utils.md
    - Plots:
      - reference/evals/plots/index.md
      - components.py: reference/evals/plots/components.md
      - barchart.py: reference/evals/plots/barchart.md
      - facetbars.py: reference/evals/plots/facetbars.md
      - sankey.py: reference/evals/plots/sankey.md
      - timeseries.py: reference/evals/plots/timeseries.md
    - Views:
      - reference/evals/views/index.md
      - balances.py: reference/evals/views/balances.md
      - balances_timeseries.py: reference/evals/views/balances_timeseries.md
      - common.py: reference/evals/views/common.md
      - capacities.py: reference/evals/views/capacities.md
      - demand.py: reference/evals/views/demand.md
      - price.py: reference/evals/views/price.md
      - sankey.py: reference/evals/views/sankey.md
- Explanations:
  - explanations/index.md
  - Data Flows:
    - explanations/data-flows/index.md
    - Industrial Demand: explanations/data-flows/industrial-demand.md
    - Heat Demand: explanations/data-flows/heat-demand.md
    - Road Mobility Demand: explanations/data-flows/road-demand.md
  - National CO2 Balance: explanations/co2-balancing.md
  - TYNDP H2 Import Infrastructure: explanations/h2-imports.md
  - Electricity Grid:
    - explanations/electricity-grid/index.md
    - NUTS3 Clustering: explanations/electricity-grid/nuts3-osm-data.md
    - OSM-AT Base Network: explanations/electricity-grid/osm-lines-at.md
    - Transmission Limits: explanations/electricity-grid/electricity-transmission.md
    - TYNDP Transmission Trajectories: explanations/electricity-grid/tyndp-transmission-trajectories.md
  - Gas Grid:
    - Gas Pipeline Capacities: explanations/gas-grid/modify-brownfield-gas-network-AT.md
    - Blocking Russian Gas Imports: explanations/gas-grid/prevent-russian-gas-imports.md
  - Brownfield:
    - Open-TYNDP Trajectories: explanations/brownfield/open-tyndp.md
    - Gas Storage Capacities: explanations/brownfield/gas-storage-capacities.md
    - Austrian Biogas-to-Power Plants: explanations/brownfield/biogas-power-plants-AT.md
  - Renewable Energy Potentials:
    - KLIEN Potentials: explanations/renewable-energy-potentials/klien-potentials.md
    - Photovoltaic Potentials: explanations/renewable-energy-potentials/pv-potentials.md
    - Wind Power Potentials: explanations/renewable-energy-potentials/wind-potentials.md
  - Hydroelectric Resources:
    - Inflow Calculation and Application: explanations/hydro-inflow.md
    - Hydro Capacity Trajectories: explanations/hydro-capacity-trajectories.md
  - Generic Capacity Trajectories: explanations/capacity-trajectories.md
  - Regulatory Requirements:
    - explanations/regulatory-requirements/index.md
    - EAG Net-Zero Electricity: explanations/regulatory-requirements/eag-net-zero-electricity.md
  - Biogas-to-gas and Biogas-to-power: explanations/biogas.md

theme:
  name: "material"
  logo: assets/logo.png
  favicon: assets/logo.png
  palette:
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
  - media: "(prefers-color-scheme: light)"
    scheme: default
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode
  features:
  - navigation.indexes
  - navigation.tracking
  - navigation.footer
#  - navigation.tabs
  - content.footnote.tooltips
  - content.code.copy
  - content.code.select
  - content.code.annotate
  - toc.follow
  - social

extra:
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/aggm-ag/pypsa-at
    name: github
  generator: true

copyright: Copyright &copy; 2024 - 2025 Austrian Gas Grid Management AG - all rights reserved.

plugins:
- search
- badges
- autorefs
- plotly
- marimo
- table-reader
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        inventories:
        - url: https://docs.pypsa.org/latest/objects.inv
        - url: https://pypsa-eur.readthedocs.io/en/latest/objects.inv
        - url: https://pathlib.readthedocs.io/en/latest/objects.inv
        - url: https://pandas.pydata.org/pandas-docs/stable/objects.inv
        - url: https://numpy.org/doc/stable/objects.inv
        - url: https://docs.python.org/3/objects.inv
        options:
          docstring_style: numpy
          show_source: true
          show_inheritance_diagram: false
          annotations_path: full
          filters:
          - "!^_"    # hide private members

# https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/
markdown_extensions:
- attr_list
- pymdownx.emoji:
    emoji_index: !!python/name:material.extensions.emoji.twemoji
    emoji_generator: !!python/name:material.extensions.emoji.to_svg
- codehilite
- admonition
- pymdownx.details
- pymdownx.snippets
- pymdownx.tabbed:
    alternate_style: true
- pymdownx.superfences:
    custom_fences:
    - name: plotly
      class: mkdocs-plotly
      format: !!python/name:mkdocs_plotly_plugin.fences.fence_plotly
    - name: mermaid
      class: mermaid
      format: !!python/name:pymdownx.superfences.fence_code_format
- tables
- md_in_html
- pymdownx.arithmatex:
    generic: true

extra_javascript:
- https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
- https://cdn.jsdelivr.net/npm/mermaid@11/dist/mermaid.min.js
- js/mermaid-theme.js

extra_css:
- assets/css/custom.css
